### ISSUE TITLE
Very imprecise coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#32]
Reviewer of data:

> 65 of the entries in the O_AMELAND dataset are "999998.9", or 1000 km, and indicate that the coordinates for these
entries cannot be trusted. If that cUIM is plausible, those 65 records should be discarded.

My answer:

> Before records are uploaded to Movebank (from which they are derived for GBIF) we calculate whether or not they constitute an outlier based on speed and angle (https://github.com/inbo/bird-tracking/blob/master/src/outliers.Rmd#L55), not (potentially imprecise) height and precision values. We exclude outliers when publishing to GBIF, we prefer not to exclude records based on the precision.

@sarahcd @tucotuco what would you suggest?

**Comment by tucotuco** [comment]
My opinion is that the coordinateUncertaintyInMeters is there so that users can filter out records that are not fit for their purpose. We do not know all of the questions that might be asked, and for which ones 1000km of uncertainty makes no difference. Let all the records be shared with their uncertainties and let the user do with them what they need to rather than pre-filter them.

**Comment by sarahcd** [comment]
Agree again with @tucotuco. These values in Movebank are as provided as-is by the sensor or the data owner. Often, records with high horizontal error estimates are clear outliers and can be flagged as such by the user, but this isn't always the case.
