### ISSUE TITLE
Number of decimals in coordinates

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#33]
Reviewer of data:

> There is also minimal correlation between coordinate precision and cUIM. Four entries with 3 decimal places in
decimalLatitude have cUIM 2.8, 3.5, 4 and 5.9, although the precision in latitude for 3 decimal places is ±55.5 m
(https://en.wikipedia.org/wiki/Decimal_degrees#Precision).
(There are 256 decimalLatitude entries with 15 decimal places, e.g. "53.165282500000004". These have an implied
uncertainty of ±0.055 nanometers, or roughly half an atomic radius, and should have been rounded.)

My answer:

> The decimal places of the coordinates are as is, i.e. how these are recorded in the source database and/or recorded by Movebank. Unfortunately that does include false precision (e.g. trailing 000 being dropped or more decimals than reasonable), but we prefer to provide the raw value (as available in the source record), rather than rounding/extending zeros.

@sarahcd @tucotuco what would you suggest? Should we round/extend?

**Comment by tucotuco** [comment]
I think it is important to be very clear on the concepts involved here, for which [Chapter 1.6 in Georeferencing Best Practices](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#accuracy-error-bias-precision-false-precision-and-uncertainty) is highly recommended. For example, "precision in latitude for 3 decimal places is ±55.5 m". The precision for 3 decimal places is 0.001. The uncertainty due to this precision is latitude dependent and 132m at 50 degrees N or S (see http://georeferencing.org/georefcalculator/gc.html).

As for, "an implied uncertainty of ±0.055 nanometers". This is a misconception. The coordinate precision is not an attribute reliably detectable or meaningful from the coordinates alone, it is an attribute that must be recorded separately to inform better the meaning of the coordinates.

My suggestion, explicitly record the actual precision if it is known (see [dwc:coordinatePrecision](https://dwc.tdwg.org/terms/#dwc:coordinatePrecision)). Do not pad the coordinates with '0's. Decimal coordinates are numbers, not strings, and the number of decimal places of the decimal coordinate fields should never be used alone to divine the real precision. Truncating or not makes no real difference, except that if you do it, maintain the result faithfully rounded to seven digits.
Coordinates with more than 7 decimal places are demonstrating false precision that is an artifact of floating point arithmetic in computers and is an introduced error. Maintaining seven digits is useful because it guarantees reversible coordinate transformations.

**Comment by peterdesmet** [comment]
Given that we record horizontal accuracy (https://github.com/inbo/movepub/issues/31) separately in `coordinateUncertaintyInMeters` and that we have no better source for the precision of the coordinates (i.e. no `dwc:coordinatePrecision`), would you then advise to keep the coordinates as is? Or round/pad to 7 digits?

**Comment by tucotuco** [comment]
If you do not know the actual coordinate precision, I would just leave the coordinates as they are. If you truncate them you lose the information that someone has a database that isn't very good at floating point numbers. ;-)

**Comment by sarahcd** [comment]
Agreed with the solution here. To clarify, Movebank imports data as they are provided by equipment manufacturers or researchers via their data files, which may have been reformatted or converted in all sorts of ways prior to import. Numbers with 15 decimal places, for example, could come from converting coordinates originally collected using a UTM format to decimal degrees. We do not attempt to make assumptions about precision or change these user-provided values. Retaining user-provided values helps users managing ongoing studies by minimizing semi-duplicate records and differences between local and imported data that can cause problems with data management and analysis.
