### ISSUE TITLE
Title and first paragraph in `write_eml()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/movepub#76]
See https://www.gbif.org/dataset/6c860eb3-83ba-48c3-9328-a7b3c7a3c7b4

1. I think the `[subsampled representation]` can be removed from the title. Camtrap DP to Darwin Core are also subsampled representations (animals only) and any transformation to Darwin Core will loose some information. I think it's better to keep the original title as is. Ping @timrobertson100
2. I think what we currently add as the first paragraph "This animal tracking dataset is derived from ..." should be moved to the last paragraph, as it is more about processing than a general introduction. So:

> HG_OOSTENDE - Herring gulls (Larus argentatus, Laridae) breeding at the southern North Sea coast (Belgium) is a bird tracking dataset published by the [Research Institute for Nature and Forest (INBO)](https://www.inbo.be/en). It contains animal tracking data collected by the LifeWatch GPS tracking network for large birds (http://lifewatch.be/en/gps-tracking-network-large-birds) for the project/study HG_OOSTENDE, using trackers developed by the University of Amsterdam Bird Tracking System (UvA-BiTS, http://www.uva-bits.nl/). The study has been operational since 2013. In total 60 individuals of European Herring gull (Larus argentatus) have been tagged in or near their breeding area at the southern North Sea coast (Ostend and Zeebrugge in Belgium), mainly to study their habitat use. Data are periodically uploaded from the UvA-BiTS database to Movebank and from there archived on Zenodo (see https://github.com/inbo/bird-tracking).
> 
> This dataset was collected using infrastructure provided by VLIZ and INBO funded by Research Foundation - Flanders (FWO) as part of the Belgian contribution to LifeWatch.
> 
> Data have been standardized to Darwin Core using the [movepub](https://inbo.github.io/movepub/) R package and are downsampled to the first GPS position per hour.

I wonder if we even need to mention:

> This animal tracking dataset is derived from Stienen et al. (2022, https://doi.org/10.5281/zenodo.6594838) a deposit of Movebank study [986040562](https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study986040562).

Since the DOI is kept the same.

**Comment by sarahcd** [comment]
My suggestion would be to keep that last sentence ("this animal tracking dataset is derived..."). While the DOI is retained, as displayed on the [GBIF page](https://www.gbif.org/dataset/6c860eb3-83ba-48c3-9328-a7b3c7a3c7b4#description) it is in the context of "how to cite", rather than "check out the complete/original data source". Likewise, if you go to ["How to cite"](https://www.gbif.org/dataset/6c860eb3-83ba-48c3-9328-a7b3c7a3c7b4#citation), with the proposed change, users are directed to cite the data using the DOI but as accessed by GBIF, and not advised to consult the original source for more information. 

Caveat is that I am representing a naive user here, and if this same situation is a typical case for lots of data types, and it is to be assumed that all GBIF representations involve a loss of context and information, maybe it is unnecessary. I do think the human readable link back to the full dataset/context would help make other movement ecologists comfortable sharing their data on GBIF.

**Comment by peterdesmet** [comment]
Ok, so maybe the last paragraph can say:

> Data have been standardized to Darwin Core using the [movepub](https://inbo.github.io/movepub/) R package and are 
downsampled to the first GPS position per hour. The original data are available in Stienen et al. (2022, https://doi.org/10.5281/zenodo.6594838), a deposit of Movebank study [986040562](https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study986040562).

**Comment by sarahcd** [comment]
Looks great!
